name = "board-games-hub"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"
[[durable_objects.bindings]]
# Le nom que nous utiliserons dans notre code pour accéder à la classe du DO.
name = "GAME_ROOM_DO" 
# Le nom de la classe que nous allons exporter dans notre fichier de code.
class_name = "GameRoomDurableObject"
[[migrations]]
tag = "v1" # Un nom pour cette version de vos objets
new_classes = [ "GameRoomDurableObject" ]