name = "board-games-hub" 
main = "functions/api/[[path]].js" 
compatibility_date = "2024-04-05" 


[build]
command = "npm run build" # Assurez-vous que ce script build bien votre client et serveur


[pages_build_output]

dir = "dist" 

[[durable_objects.bindings]]
name = "GAME_ROOM_DO"
class_name = "GameRoomDurableObject"
script_name = "room-do-worker" 