name = "board-game-hub" 
main = "functions/api/[[path]].js" 
compatibility_date = "2024-04-05" 


[build]
command = "npm run build"


pages_build_output_dir = "dist/spa"

durable_objects.bindings_name = "GAME_ROOM_DO"
class_name = "GameRoomDurableObject"
script_name = "room-do-worker" 